travis:
  secure:
    BINSTAR_TOKEN: quXML4ed1orLe1fMvhiv3wrWUhiUHFp22xIokHfQ4JJGD4fDM7PoKQ3pmzPPo7HxPE9VTZbO7ZquqmMhaVZFvbJrt9P3v2u8B4+I/yXkZaSafscpMpTHllgFwPrsZXD7gHHo7v3rsa4FYsG0j28L5m+REHIV4awYpY+Z+tPqA4axB5tARvmR2lhyDMivM1YwTBQMFCa05Qn/BSykpE1Pwh9ImBX6WKxLbiVDZnYJMIvqG5ROQ6lHkfJkKmu2fq7E6SugmS4nPRqw9c6XeO8MZXHTGLZRaZ1fOqUi+kxszGglvnz0MBcgDRmYh1eC1dmKVjz+e7PMIsr2bZQCOb3xQKhFJtucRP01gnuY8N5BCdNHBXZ4KfuLxCpuqecx5BIj0ZAbobP6NEPSXWhJHmDyIA9gIXrP9ktodNJLFeJgbu/AsvxG6gfQvggnHI8TCTswQiGXtdv5vYXor9CCXwlX62JdzNd0seqnaqlwZGs4yqZlpH5j/Xh2j+5pBIef1FaOUWHWveeURGVj6lRnnDvIlJ1XuoYZs5SIMuVErzsnihvoHzE1wN38AUhqe6djKvNtyLtyrbjCpcoxovRP1RWepshNYapVFxGD073+mBOMcvxA/YmjviAdp3KBu8sUbFYeNT+y5np9uuBgtsMF44P19B33vkJEczriJjmcbbEyePM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
